name: Build and Deploy Docs
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.15'
    - name: Install and Build Docs
      run: |
        npm install -g @compodoc/compodoc
        npx compodoc -p tsconfig.json -d docs -n "MobileSpectrum Documentation" src
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: docs
      